[package]
name = "eliasfl-chess"
version = "1.0.0"
edition = "2018"
rust-version = "1.53.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
